---
- name: System group
  group:
    name: "{{ alfred__group_name }}"
    gid: "{{ alfred__group_id }}"

- name: System user
  user:
    name: "{{ alfred__user_name }}"
    uid: "{{ alfred__user_id }}"
    group: "{{ alfred__group_name }}"
    groups: docker
    home: "{{ alfred__user_home }}"
    shell: "{{ alfred__user_shell }}"

- name: Ansible modules dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3-pip=9.0.1-2+rpt2
    - virtualenv=15.1.0+ds-1
    - python-docker=1.9.0-1

- name: System dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: no
  vars:
    packages:
      - jq=1.5+dfsg-1.3
      - git

- name: PiP dependencies
  pip:
    name:
      - docker==4.4.4
    state: present

- name: Folders
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ alfred__user_name }}"
    group: "{{ alfred__group_name }}"
    mode: 0755
  when:
    - item != "/tmp"
    - item != "/var/tmp"
  loop:
    - "{{ alfred__path_logs }}"
    - "{{ alfred__path_data }}"
    - "{{ alfred__path_tmp }}"
    - "{{ alfred__docker_path_config }}"
  
- name: Log files
  copy:
    content: ""
    dest: "{{ item }}"
    force: no
    owner: "{{ alfred__user_name }}"
    group: "{{ alfred__group_name }}"
    mode: 0644
  with_items:
    - "{{ alfred__log_default }}"
    - "{{ alfred__log_amazon_user_agent_stats_hit }}"
    - "{{ alfred__log_amazon_user_agent_stats_fail }}"

- name: Set variable for Logrotate Ansible template
  set_fact:
    alfred_log_files:
      - "{{ alfred__log_default }}"
      - "{{ alfred__log_events }}"
      - "{{ alfred__log_birthdays }}"
      - "{{ alfred__log_amazon }}"

- name: Logrotate config file
  template: 
    src: alfred.logrotate.j2
    dest: /etc/logrotate.d/alfred
    owner: root
    group: root
    mode: 0644

- name: Git repository download
  git:
    repo: "https://{{ alfred__git_user }}:{{ alfred__git_pass }}@{{ alfred__git_server }}/{{ alfred__git_repo }}"
    dest: "{{ alfred__path_tmp }}/alfred"
    version: "{{ alfred__git_version }}"
    force: yes
  check_mode: no
  changed_when: False

- name: Configuration setting (Bot settings)
  shell: |
    jq '.DEFAULT.BOT_TOKEN="{{ alfred__bot_token }}"' {{ alfred__path_tmp }}/alfred/config/config.json > {{ alfred__path_tmp }}/alfred/config/config.tmp
    jq '.DEFAULT.CLIENT_IDS=["{{ alfred__bot_client_ids[0] }}", "{{ alfred__bot_client_ids[1] }}"]' {{ alfred__path_tmp }}/alfred/config/config.tmp > {{ alfred__path_tmp }}/alfred/config/config.json
  check_mode: no
  changed_when: False

- name: Configuration settings (Pre-defined internal Docker locations)
  shell: |
    jq '.DEFAULT.LOG_FILE="/alfred/log/alfred.log"' {{ alfred__path_tmp }}/alfred/config/config.json > {{ alfred__path_tmp }}/alfred/config/config.tmp
    jq '.EVENTS.LOG_FILE="/alfred/log/alfred.log"' {{ alfred__path_tmp }}/alfred/config/config.tmp > {{ alfred__path_tmp }}/alfred/config/config.json
    jq '.BIRTHDAYS.LOG_FILE="/alfred/log/alfred.log"' {{ alfred__path_tmp }}/alfred/config/config.json > {{ alfred__path_tmp }}/alfred/config/config.tmp
    jq '.AMAZON.LOG_FILE="/alfred/log/alfred.log"' {{ alfred__path_tmp }}/alfred/config/config.tmp > {{ alfred__path_tmp }}/alfred/config/config.json
    jq '.EVENTS.DB_FILE="/alfred/data/events.json"' {{ alfred__path_tmp }}/alfred/config/config.json > {{ alfred__path_tmp }}/alfred/config/config.tmp
    jq '.BIRTHDAYS.DB_FILE="/alfred/data/birthdays.json"' {{ alfred__path_tmp }}/alfred/config/config.tmp > {{ alfred__path_tmp }}/alfred/config/config.json
    jq '.AMAZON.DB_FILE="/alfred/data/amazon.json"' {{ alfred__path_tmp }}/alfred/config/config.json > {{ alfred__path_tmp }}/alfred/config/config.tmp
    jq '.AMAZON.USER_AGENT_HIT_FILE="{{ alfred__log_amazon_user_agent_stats_hit }}"' {{ alfred__path_tmp }}/alfred/config/config.tmp > {{ alfred__path_tmp }}/alfred/config/config.json
    jq '.AMAZON.USER_AGENT_FAIL_FILE="{{ alfred__log_amazon_user_agent_stats_fail }}"' {{ alfred__path_tmp }}/alfred/config/config.json > {{ alfred__path_tmp }}/alfred/config/config.tmp
  check_mode: no
  changed_when: False

- name: Configuration settings (Metrics backend)
  shell: |
    jq '.AMAZON.GRAPHITE_SERVER="{{ alfred__tsdb_server }}"' {{ alfred__path_tmp }}/alfred/config/config.tmp > {{ alfred__path_tmp }}/alfred/config/config.json
  check_mode: no
  changed_when: False

- name: Locate the configuration file
  copy:
    src: "{{ item.source }}" 
    remote_src: yes
    dest: "{{ item.dest }}"
    owner: "{{ alfred__user_name }}"
    group: "{{ alfred__group_name }}"
    mode: 0644
  loop:
    - { source: "{{ alfred__path_tmp }}/alfred/config/config.json", dest: "{{ alfred__docker_path_config }}/config.json" }
  notify:
    - Restart Systemd service

- name: Delete the downloaded git repository
  file:
    path: "{{ alfred__path_tmp }}/alfred"
    state: absent
  check_mode: no
  changed_when: False

- name: Create Docker containter
  docker_container:
    name: alfred
    image: "alfred:{{ alfred__docker_tag }}"
    state: present
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ alfred__path_data }}:/alfred/data"
      - "{{ alfred__docker_path_config }}:/alfred/config"
      - "{{ alfred__path_logs }}:/alfred/log"
      - "{{ alfred__log_amazon_user_agent_stats_hit }}:{{ alfred__log_amazon_user_agent_stats_hit }}"
      - "{{ alfred__log_amazon_user_agent_stats_fail }}:{{ alfred__log_amazon_user_agent_stats_fail }}"
  notify:
    - Restart Systemd service

- name: Systemd service file
  copy:
    src: docker/alfred.service
    dest: /lib/systemd/system/alfred.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Systemd service

- name: Locate Cron files
  copy:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { source: "docker/events.cron", dest: "/etc/cron.d/events" }
    - { source: "docker/birthdays.cron", dest: "/etc/cron.d/birthdays" }
    - { source: "docker/amazon.cron", dest: "/etc/cron.d/amazon" }
...
